wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712467129.0
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 2
      - 3
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.12.0
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: relu
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 32
data_aug:
  desc: null
  value: true
dropout:
  desc: null
  value: 0
epochs:
  desc: null
  value: 25
filter_organization:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
neurons_in_dense_layer:
  desc: null
  value: 512
number_initial_filters:
  desc: null
  value: 128
size_filters:
  desc: null
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
