wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0.1
epochs:
  value: 5
filter_organization:
  value: 0.5
learning_rate:
  value: 0.001
neurons_in_dense_layer:
  value: 512
number_initial_filters:
  value: 128
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
