wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 128
data_aug:
  value: true
dropout:
  value: 0.1
epochs:
  value: 20
filter_organization:
  value: 0.5
learning_rate:
  value: 0.0003
neurons_in_dense_layer:
  value: 32
number_initial_filters:
  value: 16
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
