wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.1
epochs:
  value: 8
filter_organization:
  value: 1
learning_rate:
  value: 0.0001
neurons_in_dense_layer:
  value: 256
number_initial_filters:
  value: 64
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
