wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0
epochs:
  value: 10
filter_organization:
  value: 2
learning_rate:
  value: 0.0001
neurons_in_dense_layer:
  value: 64
number_initial_filters:
  value: 16
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
