wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: 0.5
learning_rate:
  value: 0.0005
neurons_in_dense_layer:
  value: 128
number_initial_filters:
  value: 128
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
