wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 128
data_aug:
  value: true
dropout:
  value: 0
epochs:
  value: 5
filter_organization:
  value: 2
learning_rate:
  value: 0.001
neurons_in_dense_layer:
  value: 512
number_initial_filters:
  value: 128
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
