wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 128
data_aug:
  value: true
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: 1
learning_rate:
  value: 0.0003
neurons_in_dense_layer:
  value: 64
number_initial_filters:
  value: 128
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
