wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0
epochs:
  value: 10
filter_organization:
  value: 1
learning_rate:
  value: 0.001
neurons_in_dense_layer:
  value: 1024
number_initial_filters:
  value: 32
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
