wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.1
epochs:
  value: 8
filter_organization:
  value: 0.5
learning_rate:
  value: 0.001
neurons_in_dense_layer:
  value: 64
number_initial_filters:
  value: 32
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
