wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.2
epochs:
  value: 8
filter_organization:
  value: 2
learning_rate:
  value: 0.0005
neurons_in_dense_layer:
  value: 128
number_initial_filters:
  value: 64
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
