wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: false
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.3
epochs:
  value: 8
filter_organization:
  value: 1
learning_rate:
  value: 0.0003
neurons_in_dense_layer:
  value: 1024
number_initial_filters:
  value: 128
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
