wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0
epochs:
  value: 5
filter_organization:
  value: 0.5
learning_rate:
  value: 0.0001
neurons_in_dense_layer:
  value: 256
number_initial_filters:
  value: 32
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
