wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: 1
learning_rate:
  value: 0.0003
neurons_in_dense_layer:
  value: 32
number_initial_filters:
  value: 32
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
