wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0
epochs:
  value: 20
filter_organization:
  value: 0.5
learning_rate:
  value: 0.0001
neurons_in_dense_layer:
  value: 512
number_initial_filters:
  value: 64
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
