wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: 0.5
learning_rate:
  value: 0.0005
neurons_in_dense_layer:
  value: 1024
number_initial_filters:
  value: 128
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
