wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0
epochs:
  value: 5
filter_organization:
  value: 2
learning_rate:
  value: 0.0003
neurons_in_dense_layer:
  value: 32
number_initial_filters:
  value: 64
size_filters:
  value:
  - 11
  - 9
  - 7
  - 5
  - 3
