wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: 1
learning_rate:
  value: 0.0001
neurons_in_dense_layer:
  value: 1024
number_initial_filters:
  value: 128
size_filters:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
