wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712486495.0
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 2
      - 3
      - 9
      - 41
      - 55
      - 103
      3:
      - 17
      - 23
      - 37
      4: 3.12.0
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
